services:
  frontend:
    env_file:
      - .env.local
    build:
      context: .
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
        NEXT_PUBLIC_AUTH_CLIENT_ID: ${NEXT_PUBLIC_AUTH_CLIENT_ID}
    ports:
      - "3002:3000"
    restart: unless-stopped
    mem_limit: 128m
    networks:
      - ai-audio-network

networks:
  ai-audio-network:
    external: true
